### ISSUE TITLE
Raw print function

### ISSUE THREAD

**Issue by devnoname120** [psxdev/debugnet#4]
Would it be possible to add a print function that would just send text?
I would like to implement my own logging system for a project, and such a function would make it easier.

**Comment by psxdev** [comment]
debugNetUDPPrintf already do that

debugNetUDPPrintf("This is a test\n");

**Comment by devnoname120** [comment]
It copies 2048 bytes even if there is no formatting needed.
Since the change is trivial, I think it's worth having it. I added a commit to make the relationship between the two functions more obvious.
